repos:
- repo: local
  hooks:
  - id: flake8
    name: Run flake8
    language: system
    entry: flake8
    types: [file, python]
  - id: black
    name: Run black code-formatter
    language: system
    entry: black
    types: [file, python]
  - id: contrib
    name: Update contributors.py from CONTRIBUTORS.md
    language: system
    entry:  ./tools/contrib_to_about.py
    args: [--git-add]
    pass_filenames: false
    files: CONTRIBUTORS.md
  - id: pipenv-setup
    name: Sync pipfile dependency changes to setup.py
    language: system
    entry: pipenv-setup
    args: [sync, --pipfile]
    pass_filenames: false
    files: Pipfile
  - id: pytest
    name: Run unit tests
    language: system
    entry: pytest
    pass_filenames: false
    files: ^(soundcraft|test)/
    types: [file, python]
